---
image: 'docker-registry.dexguru.biz/dex.guru/chainflow-deployment/chainflow-deployment/engine'
imageTag: ''
registrySecretName: registry-harbor

chainflow-engine:
  replicas:
    default: 1
  port: 8080
  limitsCpu: 1
  limitsMemory: 1G
  requestsCpu: 0.1
  requestsMemory: 125Mi
  strategyType: 'RollingUpdate'
  readnessProbe:
    path: '/health_check'
    port: '8080'
  livenessProbe:
    path: '/health_check'
    port: '8080'
  env:
    ENVIRONMENT: "stage"
    API_URL: "http://api.url.com"
    API_KEY: "key"
  ingressHost1: "chainflow-engine.dexguru.biz"
  letsencrypt:
    issuer: "letsencrypt-prod"

chainflow-engine-crossfi:
  replicas:
    default: 1
  port: 8080
  limitsCpu: 1
  limitsMemory: 1G
  requestsCpu: 0.1
  requestsMemory: 125Mi
  strategyType: 'RollingUpdate'
  readnessProbe:
    path: '/health_check'
    port: '8080'
  livenessProbe:
    path: '/health_check'
    port: '8080'
  env:
    ENVIRONMENT: "stage"
    API_URL: "http://api.url.com"
    API_KEY: "key"
  ingressHost1: "engine-crossfi.dexguru.biz"
  letsencrypt:
    issuer: "letsencrypt-prod"