---
image: 'docker-registry.dexguru.biz/dex.guru/chainflow-deployment/chainflow-deployment/engine-niftnet'
imageTag: ''
registrySecretName: registry-harbor

chainflow-engine-niftnet:
  replicas:
    default: 1
  port: 8080
  limitsCpu: 2
  limitsMemory: 2G
  requestsCpu: 1
  requestsMemory: 1024Mi
  strategyType: 'RollingUpdate'
  readnessProbe:
    path: '/health_check'
    port: '8080'
  livenessProbe:
    path: '/health_check'
    port: '8080'
  env:
    ENVIRONMENT: "stage"
    API_URL: "http://api.url.com"
    API_KEY: "key"
  ingressHost1: "chainflow-niftnet.dexguru.biz"
  letsencrypt:
    issuer: "letsencrypt-prod"
