version: "2.1"
services:
  flow-orchsetrator-engine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - API_URL=https://warehouse.dex.guru/
      - API_KEY=${WAREHOUSE_API_KEY}
    restart: on-failure
